#Collab with WalkLR and EekusGD
#PYDROID
import time
x = True
answ = ""
while x == True:
    print("Hello, i am a mini guessing NPC! try to guess the question:)")
    ques = input().lower()
    erar = "Sorry, i did not recognize the question:(, restart and try to guess the question again!"
    if ques == "the floor is lava!":
        erar = "AAAAAA, GET ON THE HOUSE!!! WE ARE ON FIRE!!"
        print(erar)
        time.sleep(2)
        print("Phew...")
        
        while True:
            print("OH NO THE LAVA IS RISING FAST! WHAT WILL YOU DO!?")
            answ = input().lower()
            if answ == "i don't care":
                print ("Ok then...")
                time.sleep(1)
                print("*kills you*")
                time.sleep(1)
                print("NO! WE DIED!")
                time.sleep(1)
                print("WHY DID YOU BETRAY ME!?")
                time.sleep(1)
                print("")
                print("BETRAY ENDING")
                print(">>end")
                x = False
                break
            else:
                print(f"{answ.upper()} IS WRONG ANSWER!")
    else:
            if ques == "fuck you":
                print("Your mom came to an eye doctor to buy an iPhone.")
                print("")
                time.sleep(1)
                print("Your dad came to get the milk but didn't get back because he was tired of your a$$.")
                print("")
                time.sleep(1)
                print("y'know why your dad is spiderman? Because he's far from home.")
                print("")
                time.sleep(1)
                while True:
                    print("Now will you say sorry!?")
                    if input().lower() == "sorry":
                        print("")
                        print("...")
                        time.sleep(1)
                        print("Ok, we go again, don't bully me>:(")
                        time.sleep(1)
                        print("")
                        print("BULLY ENDING")
                        print(">>again")
                        break
            if ques == "no you're not":
                print("What do you mean?")
                b = input().lower()
                if b == "yes you aren't":
                    print("uhhh...")
                    time.sleep(2)
                    print("")
                    print("I think you're right...")
                    time.sleep(2)
                    print("")
                    print("I WAS created by a human.")
                    time.sleep(2)
                    print("")
                    print("So maybe...")
                    time.sleep(2)
                    print("")
                    print("HAHA bro im not falling for that")
                    time.sleep(2)
                    print("")
                    print("It still counts as i am a bot:)")
                    time.sleep(2)
                    print("")
                    print("JOKE ENDING")
                    print(">>again")
            if ques == "what is str?":
                print("str is a coding command to count numbers, like if you write 'print(str(2+2))' then you will get the answer to 2 + 2, and not only plus, but also other symbols!")
                time.sleep(2)
                print("Small example:")
                print(str(2+2))
                time.sleep(2)
                print("Here i wrote print(str(2+2)) ")
                time.sleep(2)
                print("So this is what str means.")
                print("")
                print("NOTE: this does not count as an ending because it says something about programming.")
            if ques == "я русский!":
                print("Хэх, докажи:)")
                time.sleep(1)
                print("Как на русском 'fuck'? ")
                g = input().lower()
                if g == "блять":
                    print("Чо материшься, сам ты блять>:(")
                    time.sleep(1)
                    print("")
                    print("RUSSIA ENDING")
                    print(">>again")
                    time.sleep(1)
                else:
                    print("Неправильно! иностранец блять")
                    time.sleep(1)
                    print("")
                    print("WRONG RUSSIA ENDING")
                    print(">>again")
                    print("")
            if ques == "what is docx?":
                print("")
                print("IP: 123.12.23")
                time.sleep(1)
                print("NW: Onlime_15")
                time.sleep(1)
                print("Parents name: Sergey, irina")
                time.sleep(1)
                print("Your name: Andrew")
                time.sleep(1)
                print("Youtube: https://youtu.be/...")
                time.sleep(1)
                print("Phone: +7 968 012 25-50")
                time.sleep(1)
                print("Your phone: vivo Y36")
                time.sleep(1)
                print("IQ: 86")
                time.sleep(1)
                print("Friends: 158")
                time.sleep(1)
                print("UserID: 68367uhK62hsJ")
                time.sleep(1)
                print("Second account: Bodil")
                time.sleep(1)
                print("")
                print("This is what DOCX mean.")
                time.sleep(1)
                print("")
                print("DOXXED ENDING")
                print(">>again")
                time.sleep(1)
            if ques == "are you a paid bot?":
                print("")
                print("Hey, you're trying to prank me!:) If you asked that then how do i speak to you? i am a completely free bot to ask programmed questions created by python (pydroid 3)! Yes, i am actually free and fully with no rules, but don't say 18+, there are kids>:(")
                print("")
                time.sleep(5)
            if ques == "question":
                print("")
                print("OH MY...")
                time.sleep(0.5)
                print("HOW DID YOU GEUSS THATTAT!?!?!??")
                time.sleep(2)
                print("THATS IMPOSABAL!")
                time.sleep(1)
                print("OH MY GOD!!!11")
                time.sleep(1)
                print("")
                print("IMPOSSIBLE(?) ENDING")
                print(">>again")
                time.sleep(1)
            if ques == "repeat hello 100 times":
                for i in range(100):
                    print("hello " + str(i + 1))
                    time.sleep(0.1)
                print("")
                print(">>repeated")
                time.sleep(0.5)
                print(">>again")
                time.sleep(1)
            else:
                print("Sorry, i did not recognize the question:(, restart and try to guess the question again!")
            print("") 