#PYDROID
import time
print("hello:)")
id = "save/Keyboard"
afg = ""
time.sleep(8)
print("")
print("KEYBOARD HACKED!")
time.sleep(3)
while True:
    print("FILLING BYTES...")
    print("")
    print("FLOODING...")
    print("")
    print("SPAMMING...")
    print("")
    print("REPEATING...")
    print("")
    print("DELETING...")
    print("")
    print("ANDROID.FOLDER = FALSE")
    print("")
    print("SYSTEM = FALSE")
    print("")
    print("BASE.APK = FALSE")
    print("")
    print(f'{afg.upper()} LOL')
    print("")
    print("HACKING...")
    print("")
    print("LOADING...")
    print("")
    print("FINDING ALT ACCOUNTS...")
    print("")
    print("DONE! ACCOUNTS DELETED!")
    print("")